[project]
name = "analytical-platform-airflow-cadet-deployer"
version = "0.1.0"
description = "A collection of scripts to deploy Airflow CaDeT datasets"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.42.29",
]
